services:
    _defaults:
        public: true

    flasher.config:
        class: Flasher\Prime\Config\Config
        arguments:
            - []

    flasher:
        class: Flasher\Prime\Flasher
        arguments:
            - '@flasher.config'

    flasher.notification_factory:
        class: Flasher\Prime\Factory\NotificationFactory
        arguments:
            - '@flasher.storage_manager'
        tags:
            - { name: 'flasher.factory', alias: 'template' }

    flasher.storage_factory:
        class: Flasher\Symfony\Storage\StorageFactory
        arguments:
            - '@request_stack'

    flasher.storage:
        class: Flasher\Prime\Storage\StorageInterface
        factory: ['@flasher.storage_factory', '__invoke']

    flasher.storage_manager:
        class: Flasher\Prime\Storage\StorageManager
        arguments:
            - '@flasher.storage'
            - '@flasher.event_dispatcher'

    flasher.filter:
        class: Flasher\Prime\Filter\Filter

    flasher.event_dispatcher:
        class: Flasher\Prime\EventDispatcher\EventDispatcher

    flasher.event_listener.filter_listener:
        class: Flasher\Prime\EventDispatcher\EventListener\FilterListener
        public: false
        arguments:
            - '@flasher.filter'
        tags:
            - { name: 'flasher.event_subscriber' }

    flasher.event_listener.post_flush_listener:
        class: Flasher\Prime\EventDispatcher\EventListener\RemoveListener
        public: false
        tags:
            - { name: 'flasher.event_subscriber' }

    flasher.event_listener.stamps_listener:
        class: Flasher\Prime\EventDispatcher\EventListener\StampsListener
        public: false
        tags:
            - { name: 'flasher.event_subscriber' }

    flasher.twig.extension:
        class: Flasher\Symfony\Twig\FlasherTwigExtension
        arguments:
            - '@flasher.response_manager'
        tags:
            - { name: 'twig.extension' }

    flasher.resource_manager:
        class: Flasher\Prime\Response\Resource\ResourceManager
        arguments:
            - '@flasher.config'
            - '@flasher.template_engine'

    flasher.response_manager:
        class: Flasher\Prime\Response\ResponseManager
        arguments:
            - '@flasher.storage_manager'
            - '@flasher.event_dispatcher'
            - '@flasher.resource_manager'

    flasher.presenter.html:
        class: Flasher\Prime\Response\Presenter\HtmlPresenter
        tags:
            - { name: 'flasher.presenter', alias: 'html' }

    flasher.presenter.array:
        class: Flasher\Prime\Response\Presenter\ArrayPresenter
        tags:
            - { name: 'flasher.presenter', alias: 'array' }

    flasher.session_listener:
        class: Flasher\Symfony\EventListener\SessionListener
        arguments:
            - '@flasher.config'
            - '@flasher'
            - '@flasher.response_manager'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.response' }

    flasher.template_engine:
        class: Flasher\Symfony\Template\TwigEngine
        arguments:
            - '@twig'

    Flasher\Prime\Config\Config: '@flasher.config'
    Flasher\Prime\Flasher: '@flasher'
    Flasher\Prime\EventDispatcher\EventDispatcher: '@flasher.event_dispatcher'
    Flasher\Symfony\Storage\Storage: '@flasher.storage'
    Flasher\Prime\Storage\StorageManager: '@flasher.storage_manager'
    Flasher\Prime\Filter\Filter: '@flasher.filter'
    Flasher\Prime\Factory\NotificationFactory: '@flasher.notification_factory'
    Flasher\Symfony\Template\TwigEngine: '@flasher.template_engine'

    Flasher\Prime\Config\ConfigInterface: '@flasher.config'
    Flasher\Prime\FlasherInterface: '@flasher'
    Flasher\Prime\Storage\StorageManagerInterface: '@flasher.storage_manager'
    Flasher\Prime\Filter\FilterInterface: '@flasher.filter'
    Flasher\Prime\EventDispatcher\EventDispatcherInterface: '@flasher.event_dispatcher'
    Flasher\Prime\Storage\StorageInterface: '@flasher.storage'
    Flasher\Prime\Factory\NotificationFactoryInterface: '@flasher.notification_factory'
    Flasher\Prime\Template\EngineInterface: '@flasher.template_engine'
    Flasher\Prime\Response\ResponseManagerInterface: '@flasher.response_manager'
