name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for your pull request. However, you have submitted this PR on a read-only sub split of `php-flasher/php-flasher`. Please submit your PR on the https://github.com/php-flasher/php-flasher repository.<br><br>Thanks!"
