name: Running tests

on:
    push:
    pull_request:
    schedule:
        -   cron: '* * * * *'

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                symfony: [5.2.*, 5.1.*, 5.0.*, 4.4.*, 4.3.*, 4.2.*, 4.1.*, 4.0.*, 3.4.*, 3.3.*, 3.2.*, 3.1.*, 3.0.*, 2.8.*, 2.7.*]
                include:
                    -   symfony: 5.2.*
                        php: 7.2
                        phpunit: 8.3.*

                    -   symfony: 5.1.*
                        php: 7.2
                        phpunit: 8.3.*

                    -   symfony: 5.0.*
                        php: 7.2
                        phpunit: 8.3.*

                    -   symfony: 4.4.*
                        php: 7.1
                        phpunit: 7.0.*

                    -   symfony: 4.3.*
                        php: 7.1
                        phpunit: 7.0.*

                    -   symfony: 4.2.*
                        php: 7.1
                        phpunit: 7.0.*

                    -   symfony: 4.1.*
                        php: 7.1
                        phpunit: 7.0.*

                    -   symfony: 4.0.*
                        php: 7.1
                        phpunit: 7.0.*

                    -   symfony: 3.4.*
                        php: 5.5
                        phpunit: 4.8.36

                    -   symfony: 3.3.*
                        php: 5.5
                        phpunit: 4.8.36

                    -   symfony: 3.2.*
                        php: 5.5
                        phpunit: 4.8.36

                    -   symfony: 3.1.*
                        php: 5.5
                        phpunit: 4.8.36

                    -   symfony: 3.0.*
                        php: 5.5
                        phpunit: 4.8.36

                    -   symfony: 2.8.*
                        php: 5.3
                        phpunit: 4.8.36

                    -   symfony: 2.7.*
                        php: 5.3
                        phpunit: 4.8.36

        name: S${{ matrix.symfony }} - P${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "symfony/symfony:${{ matrix.symfony }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    composer update --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit
